# 言語・上限・動作モード
lang: ja                # "ja" or "en"
strict_captions_only: true    # true=字幕ある動画のみ処理（Whisper不使用）
ignore_state_within_24h: true   # これが true なら 24h 内は既読でも処理

# 監視対象チャンネル（@, /c/, /user/, /channel/ 何でもOK）
channels:
  - https://www.youtube.com/channel/UCqmWJJolqAgjIdLqK3zD1QQ
  - https://www.youtube.com/channel/UC8yHePe_RgUBE-waRWy6olw
  - https://www.youtube.com/channel/UC9CZ_z2S17I46EjoOtlYrRw
  - https://www.youtube.com/channel/UC2lJYodMaAfFeFQrGUwhlaQ
  - https://www.youtube.com/channel/UC67Wr_9pA4I0glIxDt_Cpyw
  - https://www.youtube.com/channel/UC4a-Gbdw7vOaccHmFo40b9g
  - https://www.youtube.com/channel/UCBevyiJ2ierZY-0yZhfLrmQ
  - https://www.youtube.com/channel/UC4a-Gbdw7vOaccHmFo40b9g
  - https://www.youtube.com/channel/UCNU_lfiiWBdtULKOw6X0Dig
  - https://www.youtube.com/channel/UCh9nVJoWXmFb7sLApWGcLPQ
  - https://www.youtube.com/channel/UCcIXc5mJsHVYTZR1maL5l9w
  - https://www.youtube.com/channel/UCbfYPyITQ-7l4upoX8nvctg
  - https://www.youtube.com/channel/UCZHmQk67mSJgfCCTn7xBfew
  - https://www.youtube.com/channel/UCHlNU7kIZhRgSbhHvFoy72w
  - https://www.youtube.com/channel/UC9V4eJBNx_hOieGG51NZ6nA
  - https://www.youtube.com/channel/UCaG7jufgiw4p5mphPPVbqhw
  - https://www.youtube.com/channel/UCEixleMT76xDzoiEb9ZA7XA
  - https://www.youtube.com/channel/UCcdd3kS52T9Zyo-SWfj86bA
  - https://www.youtube.com/channel/UCC4NkFV-L-vVYD5z_Ei5dUA
  - https://www.youtube.com/channel/UCpLu0KjNy616-E95gPx7LZg
